/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as MainInviteRouteRouteImport } from './routes/_main/invite/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AuthJoinRouteRouteImport } from './routes/_auth/join/route'
import { Route as MainTasksIndexRouteImport } from './routes/_main/tasks/index'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainTasksCreateRouteRouteImport } from './routes/_main/tasks/create/route'
import { Route as MainTasksTaskIdRouteRouteImport } from './routes/_main/tasks/$taskId/route'
import { Route as MainTasksEditTaskIdRouteRouteImport } from './routes/_main/tasks/edit/$taskId/route'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainInviteRouteRoute = MainInviteRouteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJoinRouteRoute = AuthJoinRouteRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainTasksIndexRoute = MainTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTasksCreateRouteRoute = MainTasksCreateRouteRouteImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTasksTaskIdRouteRoute = MainTasksTaskIdRouteRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTasksEditTaskIdRouteRoute =
  MainTasksEditTaskIdRouteRouteImport.update({
    id: '/tasks/edit/$taskId',
    path: '/tasks/edit/$taskId',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof AuthJoinRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/invite': typeof MainInviteRouteRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/tasks/$taskId': typeof MainTasksTaskIdRouteRoute
  '/tasks/create': typeof MainTasksCreateRouteRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/tasks': typeof MainTasksIndexRoute
  '/tasks/edit/$taskId': typeof MainTasksEditTaskIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof AuthJoinRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/invite': typeof MainInviteRouteRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/tasks/$taskId': typeof MainTasksTaskIdRouteRoute
  '/tasks/create': typeof MainTasksCreateRouteRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/tasks': typeof MainTasksIndexRoute
  '/tasks/edit/$taskId': typeof MainTasksEditTaskIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/join': typeof AuthJoinRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_main/invite': typeof MainInviteRouteRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_main/tasks/$taskId': typeof MainTasksTaskIdRouteRoute
  '/_main/tasks/create': typeof MainTasksCreateRouteRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
  '/_main/tasks/': typeof MainTasksIndexRoute
  '/_main/tasks/edit/$taskId': typeof MainTasksEditTaskIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/invite'
    | '/onboarding'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/dashboard'
    | '/tasks'
    | '/tasks/edit/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/invite'
    | '/onboarding'
    | '/tasks/$taskId'
    | '/tasks/create'
    | '/dashboard'
    | '/tasks'
    | '/tasks/edit/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_auth/join'
    | '/_auth/login'
    | '/_main/invite'
    | '/onboarding/'
    | '/_main/tasks/$taskId'
    | '/_main/tasks/create'
    | '/_main/dashboard/'
    | '/_main/tasks/'
    | '/_main/tasks/edit/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/invite': {
      id: '/_main/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof MainInviteRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/join': {
      id: '/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthJoinRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/tasks/': {
      id: '/_main/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof MainTasksIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tasks/create': {
      id: '/_main/tasks/create'
      path: '/tasks/create'
      fullPath: '/tasks/create'
      preLoaderRoute: typeof MainTasksCreateRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tasks/$taskId': {
      id: '/_main/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof MainTasksTaskIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tasks/edit/$taskId': {
      id: '/_main/tasks/edit/$taskId'
      path: '/tasks/edit/$taskId'
      fullPath: '/tasks/edit/$taskId'
      preLoaderRoute: typeof MainTasksEditTaskIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthJoinRouteRoute: typeof AuthJoinRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthJoinRouteRoute: AuthJoinRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainInviteRouteRoute: typeof MainInviteRouteRoute
  MainTasksTaskIdRouteRoute: typeof MainTasksTaskIdRouteRoute
  MainTasksCreateRouteRoute: typeof MainTasksCreateRouteRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
  MainTasksIndexRoute: typeof MainTasksIndexRoute
  MainTasksEditTaskIdRouteRoute: typeof MainTasksEditTaskIdRouteRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainInviteRouteRoute: MainInviteRouteRoute,
  MainTasksTaskIdRouteRoute: MainTasksTaskIdRouteRoute,
  MainTasksCreateRouteRoute: MainTasksCreateRouteRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
  MainTasksIndexRoute: MainTasksIndexRoute,
  MainTasksEditTaskIdRouteRoute: MainTasksEditTaskIdRouteRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
