/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as MainInviteRouteRouteImport } from './routes/_main/invite/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AuthJoinRouteRouteImport } from './routes/_auth/join/route'
import { Route as MainSquadsIndexRouteImport } from './routes/_main/squads/index'
import { Route as MainDashboardIndexRouteImport } from './routes/_main/dashboard/index'
import { Route as MainSquadsCreateRouteImport } from './routes/_main/squads/create'
import { Route as MainSquadsSquadIdEditRouteImport } from './routes/_main/squads/$squadId.edit'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainInviteRouteRoute = MainInviteRouteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthJoinRouteRoute = AuthJoinRouteRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainSquadsIndexRoute = MainSquadsIndexRouteImport.update({
  id: '/squads/',
  path: '/squads/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardIndexRoute = MainDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSquadsCreateRoute = MainSquadsCreateRouteImport.update({
  id: '/squads/create',
  path: '/squads/create',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSquadsSquadIdEditRoute = MainSquadsSquadIdEditRouteImport.update({
  id: '/squads/$squadId/edit',
  path: '/squads/$squadId/edit',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof AuthJoinRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/invite': typeof MainInviteRouteRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/squads/create': typeof MainSquadsCreateRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/squads': typeof MainSquadsIndexRoute
  '/squads/$squadId/edit': typeof MainSquadsSquadIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof AuthJoinRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/invite': typeof MainInviteRouteRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/squads/create': typeof MainSquadsCreateRoute
  '/dashboard': typeof MainDashboardIndexRoute
  '/squads': typeof MainSquadsIndexRoute
  '/squads/$squadId/edit': typeof MainSquadsSquadIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/join': typeof AuthJoinRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_main/invite': typeof MainInviteRouteRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_main/squads/create': typeof MainSquadsCreateRoute
  '/_main/dashboard/': typeof MainDashboardIndexRoute
  '/_main/squads/': typeof MainSquadsIndexRoute
  '/_main/squads/$squadId/edit': typeof MainSquadsSquadIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/invite'
    | '/onboarding'
    | '/squads/create'
    | '/dashboard'
    | '/squads'
    | '/squads/$squadId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/invite'
    | '/onboarding'
    | '/squads/create'
    | '/dashboard'
    | '/squads'
    | '/squads/$squadId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_auth/join'
    | '/_auth/login'
    | '/_main/invite'
    | '/onboarding/'
    | '/_main/squads/create'
    | '/_main/dashboard/'
    | '/_main/squads/'
    | '/_main/squads/$squadId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/invite': {
      id: '/_main/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof MainInviteRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/join': {
      id: '/_auth/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthJoinRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/squads/': {
      id: '/_main/squads/'
      path: '/squads'
      fullPath: '/squads'
      preLoaderRoute: typeof MainSquadsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard/': {
      id: '/_main/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/squads/create': {
      id: '/_main/squads/create'
      path: '/squads/create'
      fullPath: '/squads/create'
      preLoaderRoute: typeof MainSquadsCreateRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/squads/$squadId/edit': {
      id: '/_main/squads/$squadId/edit'
      path: '/squads/$squadId/edit'
      fullPath: '/squads/$squadId/edit'
      preLoaderRoute: typeof MainSquadsSquadIdEditRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthJoinRouteRoute: typeof AuthJoinRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthJoinRouteRoute: AuthJoinRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainInviteRouteRoute: typeof MainInviteRouteRoute
  MainSquadsCreateRoute: typeof MainSquadsCreateRoute
  MainDashboardIndexRoute: typeof MainDashboardIndexRoute
  MainSquadsIndexRoute: typeof MainSquadsIndexRoute
  MainSquadsSquadIdEditRoute: typeof MainSquadsSquadIdEditRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainInviteRouteRoute: MainInviteRouteRoute,
  MainSquadsCreateRoute: MainSquadsCreateRoute,
  MainDashboardIndexRoute: MainDashboardIndexRoute,
  MainSquadsIndexRoute: MainSquadsIndexRoute,
  MainSquadsSquadIdEditRoute: MainSquadsSquadIdEditRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
